### ISSUE TITLE
Console continues sending a warning.

### ISSUE THREAD

**Issue by FIREPAWER07** [Xezard/XItemsRemover#23]
[23:05:12 WARN]: [XItemsRemover] Task #21 for XItemsRemover v1.1.5 generated an exception

java.lang.NullPointerException: null

at ru.xezard.items.remover.data.TrackingManager.clearEntities(TrackingManager.java:159) ~[?:?]

at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[CraftTask.class:?]

at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:422) [CraftScheduler.class:?]

at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831) [MinecraftServer.class:?]

at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]

at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]

at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

**Comment by sabahmax-inc** [comment]
Hi! Thanks for the report. I've opened [PR #25](https://github.com/Xezard/XItemsRemover/pull/25), which fixes this warning by safely handling null entries in `TrackingManager.clearEntities`, so the `NullPointerException` should no longer occur.
